# add the following to _config.yml file
title: JUN HYEOK (RAY) KWON
theme: jekyll-theme-minimal
email: yourname@example.com
description: >
  Data Science / Machine Learning Enthusiast  
  ğŸ“ 123-456-7890 | âœ‰ï¸ yourname@example.com

