# add the following to _config.yml file
title: JUN HYEOK (RAY) KWON
theme: jekyll-theme-minimal
description: |
  Data Science / ML Enthusiast      
  
  ğŸ“ 206-756-8945   
  
  âœ‰ï¸ junhyeok.kwon@gmail.com
  

