# add the following to _config.yml file
title: JUN HYEOK (RAY) KWON
theme: jekyll-theme-minimal
description: |
  Data Science / Machine learning Enthusiast <br><br>
  ğŸ“ 206-756-8945 <br><br>
  âœ‰ï¸ junhyeok.kwon@gmail.com

